name: Playwright Login Test (Headless Chrome)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-login-spec:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies and browsers
    - name: Install dependencies
      run: |
        npm install
        npx playwright install chromium --with-deps

    # Step 4: Run scroll.spec.js in headless Chrome
    - name: Run Scroll Spec (Headless Chrome)
      run: npx playwright test tests/scroll.spec.js --project=chromium --headed=false --reporter=html --workers=1

    # Step 5: Upload HTML report
    - name: Upload Playwright HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-login-report
        path: playwright-report
